#!/usr/bin/env python3

import multiprocessing
import subprocess
import glob

# Reads python scripts generated by process_maker.py; they contain the code we want to run, for instance ping
# The individual files (scripts) are read by glob from a local directory and glob returns a list of file names
# our files are called ping_proces1.py etc.
scripts = glob.glob("ping_process*")

# Determines the number of scripts(processes)
c = len(scripts)

def multi_ping(process):
	subprocess.run(["python3", process])

# Creating the Pool object, called process_pool and applying the function multi_ping() to all scripts
process_pool = multiprocessing.Pool(processes = c)
process_pool.map(multi_ping, scripts)
